from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("users",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("phone_number",sa.String(13),nullable=False,unique=True),sa.Column("full_name",sa.String(100),nullable=False),sa.Column("password_hash",sa.String(512),nullable=False),sa.Column("referral_code",sa.String(24),nullable=False,unique=True),sa.Column("referred_by_id",postgresql.UUID(as_uuid=True)),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["referred_by_id"],["users.id"],ondelete="SET NULL"))
    op.create_index("ix_users_phone_number","users",["phone_number"]); op.create_index("ix_users_referral_code","users",["referral_code"]); op.create_index("ix_users_referred_by_id","users",["referred_by_id"])
    op.create_table("sessions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("token_hash",sa.String(64),nullable=False,unique=True),sa.Column("csrf_hash",sa.String(64),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE")); op.create_index("ix_sessions_token_hash","sessions",["token_hash"]); op.create_index("ix_sessions_user_id","sessions",["user_id"])
    op.create_table("wallets",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False,unique=True),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE")); op.create_index("ix_wallets_user_id","wallets",["user_id"])
    op.create_table("transactions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("reference",sa.String(32),nullable=False,unique=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("transaction_type",sa.String(32),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("external_reference",sa.String(128),unique=True),sa.Column("idempotency_key",sa.String(128),unique=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="RESTRICT")); op.create_index("ix_transactions_user_id","transactions",["user_id"])
    op.create_table("ledger_entries",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("wallet_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("transaction_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("direction",sa.String(8),nullable=False),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["wallet_id"],["wallets.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["transaction_id"],["transactions.id"],ondelete="RESTRICT")); op.create_index("ix_ledger_entries_wallet_id","ledger_entries",["wallet_id"]); op.create_index("ix_ledger_entries_transaction_id","ledger_entries",["transaction_id"])
    op.create_table("referral_rules",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("level",sa.Integer(),nullable=False,unique=True),sa.Column("rate_percent",sa.Numeric(7,4),nullable=False),sa.Column("active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    for t in ["referral_rules","ledger_entries","transactions","wallets","sessions","users"]: op.drop_table(t)
